apiVersion: apps/v1
kind: Deployment
metadata:
  name: swish-interview
  labels:
    app: swish-interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swish-interview
  template:
    metadata:
      labels:
        app: swish-interview
    spec:
      containers:
        - name: swish-interview
          image: ghcr.io/kubictech/swish-interview:latest
          command: ["tail"]
          args: ["-f", "/dev/null"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
