apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: swish-interview
spec:
  parentRefs:
    - name: external-gateway
      namespace: istio-system
  hostnames:
    - "swish-interview.kubic.tech"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: swish-interview
          port: 80