name: Build and Push Container

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ main ]
  release:
    types: [released, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: false
          tags: |
            ghcr.io/${{ github.repository }}/multi-env:latest
            ghcr.io/${{ github.repository }}/multi-env:${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          input: /tmp/image.tar
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/multi-env:latest
            ghcr.io/${{ github.repository }}/multi-env:${{ github.sha }} 