name: Build and Push Container

on:
  push:
    branches:
      - main
      - dev
      - feature
    paths:
      - "docker/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
  release:
    types: [released, prereleased]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: set lower case repo name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: "${{ github.repository }}"

      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: "docker-container"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPO_LC }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          driver: docker-container
          image: ${{ env.REGISTRY }}/${{ env.REPO_LC }}
          push: false
          tags: steps.meta.outputs.tags
          outputs: |
            type=tar,dest=/tmp/image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner (non-blocking) for PRs.
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main')
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: "image"
          input: /tmp/image.tar
          format: 'table'
          exit-code: '1'
          severity: "CRITICAL,HIGH"

      - name: Run Trivy vulnerability scanner
        if: github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          input: /tmp/image.tar
          format: 'table'
          exit-code: '1'
          severity: "CRITICAL,HIGH"

      - name: Log in to GitHub Container Registry
        if: success() && (github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: success() && (github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: steps.meta.outputs.tags
